CREATE DATABASE IF NOT EXISTS FOOD_DELIVERY_ML;
CREATE SCHEMA IF NOT EXISTS FOOD_DELIVERY_ML.ML_SCHEMA;

CREATE OR REPLACE WAREHOUSE ML_WH
WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE DATABASE FOOD_DELIVERY_ML;
USE SCHEMA ML_SCHEMA;
USE WAREHOUSE ML_WH;

-- Raw CSV was loaded into DELIVERY_DATA using Snowsight.

CREATE OR REPLACE TABLE DELIVERY_ML_DATA AS
SELECT
    TRY_TO_DOUBLE(DELIVERY_PERSON_AGE) AS AGE,
    TRY_TO_DOUBLE(DELIVERY_PERSON_RATINGS) AS RATING,
    RESTAURANT_LATITUDE AS REST_LAT,
    RESTAURANT_LONGITUDE AS REST_LONG,
    DELIVERY_LOCATION_LATITUDE AS DELIVERY_LAT,
    DELIVERY_LOCATION_LONGITUDE AS DELIVERY_LONG,
    VEHICLE_CONDITION,
    TRY_TO_DOUBLE(MULTIPLE_DELIVERIES) AS MULTIPLE_DELIVERIES,
    WEATHER_CONDITIONS,
    ROAD_TRAFFIC_DENSITY,
    TYPE_OF_ORDER,
    TYPE_OF_VEHICLE,
    FESTIVAL,
    CITY,
    "Time_taken (min)" AS DELIVERY_TIME
FROM DELIVERY_DATA
WHERE TRY_TO_DOUBLE(DELIVERY_PERSON_AGE) IS NOT NULL
  AND TRY_TO_DOUBLE(DELIVERY_PERSON_RATINGS) IS NOT NULL
  AND "Time_taken (min)" IS NOT NULL;

CREATE OR REPLACE TABLE DELIVERY_FEATURES AS
SELECT
    AGE, RATING, REST_LAT, REST_LONG, DELIVERY_LAT, DELIVERY_LONG,
    VEHICLE_CONDITION, MULTIPLE_DELIVERIES,
    WEATHER_CONDITIONS, ROAD_TRAFFIC_DENSITY,
    TYPE_OF_ORDER, TYPE_OF_VEHICLE, FESTIVAL, CITY, DELIVERY_TIME,
    6371 * 2 * ASIN(
        SQRT(
            POWER(SIN(RADIANS(DELIVERY_LAT - REST_LAT) / 2), 2)
            + COS(RADIANS(REST_LAT)) * COS(RADIANS(DELIVERY_LAT))
            * POWER(SIN(RADIANS(DELIVERY_LONG - REST_LONG) / 2), 2)
        )
    ) AS DISTANCE_KM
FROM DELIVERY_ML_DATA;

SELECT COUNT(*) AS ROWS FROM DELIVERY_FEATURES;
